version: "2"

services:
  web:
    image: nginx:latest
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
      image: php:7-fpm
      restart: on-failure
      volumes:
          - ./app:/app


